---
title: "Insurance Claim Severity"
author: "Chris Greenwell"
date: "September 12, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Insurance... Friend or Foe?

Have you ever been in a car wreck? Or, have you had any property damage caused by a natural disaster? Most likely, most of the folks reading this have experienced some sort of loss caused by an accident, and the only thing worse than the loss itself, is dealing with an insurance agent!

My goal is to change your mind regarding the frustrations of the insurance claims process by establishing an algorithm to help predict the severity of a potential claim and thus allow for the correct amount of coverage to be enacted before such a claim can arise.

## Who Should Care and Why?

My client(s) for this project would be any independent or captive insurance agency who is interested in implementing an claims severity predictor as an added benefit to the agencies' respective insureds.

Insurance agencies will be able to accurately predict the cost amount of an insurance claim at a faster, more streamlined pace which will allow for more energy to devote to servicing the insureds. This, in turn, will reduce client turnover and increase client retention for the insurance agencies.

## Data Utilized

The data I will be using for this project is from the Allstate Claims Severity recruitment competition on Kaggle. Although this data is specific to the company, Allstate, the algorithm I develop will be able to be used for other insurance agencies as well.


## Approach

My approach will be to wrangle the data provided by Kaggle,  evaluate and analyze the data, and implement mathematical and statistical steps to establish an cost predicting algorithm. I will also use regression techniques and others to provide meaningful data visualization. 

The final product will be evaluated by the mean absolute error between the predicted loss and the actual loss. Below is the mean absolute error equation:

$$MAE = 1/n \sum^{n}_{i=1} \ \mid y_{i} - \hat{y}_{i}\mid$$
Where:

$$AE = \mid y_{i} - \hat{y}_{i}\mid$$
$$ActualLoss = y_{i}$$
$$Predicted Loss = \hat{y}_{i}$$
